In [52]:
import numpy as np 

# 1d array 
arr1 = np.array([1,2,3,4,5])


# 2d array 
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

#3d array 

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] ])#row2 

    # dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim) 

1
2
3


In [53]:
#shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape) 


#data type 
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64


In [54]:
#size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

5
6
18


In [55]:
# ndarray data type
arr = np.array([1,2,3]) 

print(arr.dtype)

arr = np.array([1.5,2.4,3.2]) 
print(arr.dtype)

int64
float64


In [56]:
arr = np.array([1,2,3.2]) 
# upcasted to float 
print(arr.dtype) 

#upcasted to string
arr = np.array([1,2,3.2,'hello']) 
print(arr.dtype) 


arr = np.array([1,True,3.25,'hello',]) 
print(arr.dtype) 

float64
<U32
<U32


In [57]:
# change data type/select data type
arr = np.array([1,2,300],dtype=np.int16)
print(arr.dtype)
print(arr)
# or
arr = arr.astype(np.int32)
print(arr.dtype)

#error
# arr = np.array([1,2,3.2,'hello'],dtype=np.float64) 

int16
[  1   2 300]
int32


In [58]:
lst=[10,20,30,40,40.5]
arr=np.array(lst,dtype=np.int16)
# print(arr.dtype)
# print(arr)

mixed_lst = [10, True , 'Hello' ]
arr = np.array(mixed_lst) 
# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 

matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix) 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [59]:
tpl=(10,20,30)
arr = np.array(tpl) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1


In [60]:
st={1,2,3}
arr = np.array(list(st)) 
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim) 

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [61]:
# dictionary 

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()
#keys to ndarray
arr = np.array(list(keys))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
arr = np.array(list(values))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
arr = np.array(list(items))
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


In [62]:
# creating ndarray from scratch
arr=np.zeros((2,3),dtype=np.int8)
# print(arr) 
# print(type(arr)) 
# print(arr.dtype) 
# print(arr.shape) 
# print(arr.ndim)
# print(arr.size)
arr=np.zeros_like(arr3)
print(arr) 
print(arr.shape) 

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(3, 2, 3)


In [63]:
arr=np.ones((2,3),dtype=np.int8)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
arr=np.ones_like(arr3)
print(arr) 
print(arr.shape) 

[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [64]:
arr=np.empty((4,3),dtype=np.int8)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
arr=np.empty_like(arr3)
print(arr) 
print(arr.shape) 

[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [65]:
arr=np.full((4,3),np.inf)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)
arr=np.full_like(arr3,np.inf,dtype=np.float64)
# arr=np.full_like(arr3,10)

print(arr) 
print(arr.shape) 

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
float64
(4, 3)
2
12
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]
(3, 2, 3)


In [66]:

# np.random.rand(shape) 

arr = np.random.rand(2,3) # 0 ->1 

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[0.68556547 0.11254805 0.06037571]
 [0.00999587 0.315508   0.12987788]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [67]:
# np.random.randint(start,end, shape) 

arr = np.random.randint(1,10 , (2,3))  

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[4 8 7]
 [2 9 3]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [68]:
# np.random.uniform(start,end, shape) 

arr = np.random.uniform(50,100, (3,3,4))   

print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[[[53.50853271 75.67012065 66.0197366  69.55106046]
  [68.66536465 70.15572289 67.38902344 65.11451386]
  [75.95538815 96.31636266 73.95957819 59.0156631 ]]

 [[78.44322681 98.92122883 51.57208866 54.72571585]
  [88.92954884 66.28076751 69.07623979 63.05063984]
  [61.07028726 69.1081821  88.3579166  51.19007251]]

 [[64.32450247 55.07607164 76.13107772 77.83488225]
  [97.22839322 77.06754309 53.30662977 76.68188324]
  [73.77723058 77.08161999 99.1238884  77.71231872]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


In [69]:
# np.arange(first , end , step ) -> similar to range function 

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3) 

print(arr) 
print(mat) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [70]:
# np.linspace(start , end(included) , koita) 

arr = np.linspace(0, 4 ,6)
print(arr) 
print(type(arr)) 
print(arr.dtype) 
print(arr.shape) 
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [74]:
# np.logspace(start , end(included) , koita ) 

arr = np.logspace(0 , 4 ,6, base =2) 

print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


In [73]:
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [81]:
# identity matrix 

identity_mat = np.eye(3)
print(identity_mat)
print(identity_mat.shape)

# np.eye(row , column,k) 

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)
mat = np.eye(3,4,-1)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [84]:
#indexing 

print(arr1)
print(arr2)

print(arr1[2])
arr1[2] = 100 
print(arr1)

print(arr2[0][1])
arr2[0][2]= 100

print(arr2)

[  1   2 100   4   5]
[[  1   2 100]
 [  4   5   6]]
100
[  1   2 100   4   5]
2
[[  1   2 100]
 [  4   5   6]]


In [85]:
#slicing 
#1d = arr[start:end:step] 
arr1_mod = arr1[1:4].copy()
arr1[1] = 2

arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2 100 200]
[  1   2 100   4   5]


In [91]:
#2d slicing 
# arr[ row_start : row_end : step , column_start : column_end : step ]
#getting a row 
print(arr2)
row_0 = arr2[0:1 ,]
row_1= arr2[1: , ]

print(row_0)
print(row_1)

[[  1   2 100]
 [  4   5   6]]
[[  1   2 100]]
[[4 5 6]]


In [88]:
print(arr2) 
col_0 = arr2[: ,0:1]
col_1 = arr2[:,1:2]

print(col_0)
print(col_1)

[[  1   2 100]
 [  4   5   6]]
[[1]
 [4]]
[[2]
 [5]]


In [89]:
#getting a portion 
portion = arr2[:: , 0:2] 
print(portion)

[[1 2]
 [4 5]]


In [92]:
# Advance indexing
lst = np.array([ 10 , 20 ,30 ,40 ]) 
values = lst[[0,3,1]]

print(values)

[10 40 20]


In [94]:
print(arr2)
print(arr2[[0,1] , [1,2]])

# boolean kono kichu diye
print(arr2[arr2>2])
arr2[arr2>2] = 0 

print(arr2)

[[  1   2 100]
 [  4   5   6]]
[2 6]
[100   4   5   6]
[[1 2 0]
 [0 0 0]]


In [95]:
arr  = np.array([[10,20,30] , [100,200,300] ] )

# iteration 
print(arr3)
for i in np.nditer(arr3):
    print(i)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6


In [98]:
"""You have a list of temperatures recorded in Celsius. Your task is to:
Create a NumPy array from the given list.
Convert all temperatures from Celsius to Fahrenheit. The formula is F = C* 1.8 + 32.
Print the new Fahrenheit array."""
import numpy as np
lst=[0,20,37,100]
c_array=np.array(lst)
fahren=c_array*1.8+32.
print(fahren)


[ 32.   68.   98.6 212. ]


In [100]:
"""ou have a Python list containing the lap times (in seconds) for an athlete.

Task:

Convert the list into a NumPy array.
Print the array's shape, size, and data type.
The athlete wants to see their times in minutes. Create a new array by dividing all the lap times by 60.
Print the new array of lap times in minutes
"""
lap_times = [75, 80, 95, 100, 120]
lap_array=np.array(lap_times)
print(lap_array.shape)
print(lap_array.size)
print(lap_array.dtype)
lap_times_min=lap_array/60
print(lap_times_min)

(5,)
5
int64
[1.25       1.33333333 1.58333333 1.66666667 2.        ]
