In [2]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


In [3]:
ages_arr=np.array(DF['age'])
print(ages_arr)
salaries_arr=np.array(DF['salary'])
print(salaries_arr)
print(ages_arr.dtype)
print(ages_arr.ndim)
print(ages_arr.shape)
print(ages_arr.size)
print(salaries_arr.dtype)
print(salaries_arr.ndim)
print(salaries_arr.shape)
print(salaries_arr.size)

[56 46 32 25 38 56 36 40 28 28]
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
int64
1
(10,)
10
int64
1
(10,)
10


In [4]:
print(salaries_arr)

highest_values=np.max(salaries)
print(highest_values)

lowest_salary=np.min(salaries)
print(lowest_salary)

average_salary=np.mean(salaries)
print(average_salary)

print(ages_arr)
average_age=np.mean(ages)
print(average_age)

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
89735
30769
57446.9
[56 46 32 25 38 56 36 40 28 28]
38.5


In [5]:
print(ages_arr)

ages_greater_than_30=ages_arr[ages_arr>30]
print(ages_greater_than_30)

count_older_than_30=np.count_nonzero(ages_arr>30)
print(count_older_than_30)

[56 46 32 25 38 56 36 40 28 28]
[56 46 32 38 56 36 40]
7


In [6]:
print(ages_arr)

increase_age_5_years=ages_arr+5
print(increase_age_5_years)
# print(ages_arr)

[56 46 32 25 38 56 36 40 28 28]
[61 51 37 30 43 61 41 45 33 33]


In [7]:
print(salaries_arr)
sum_of_all_salaries=np.sum(salaries_arr)
print(sum_of_all_salaries)

difference_between_max_min_salary= np.max(salaries_arr)-np.min(salaries_arr)
print(difference_between_max_min_salary)

[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
574469
58966


In [8]:
df=pd.read_csv("employees.csv")
df
print(df.head(5))
df.info()
df.describe()

   id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

In [9]:
display_column=df[['id','age','salary']]
last_3=display_column.tail(3)
print(last_3)

   id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311


In [10]:
who_work_in_IT=df.loc[df['dept']=='IT']
print(who_work_in_IT)

total_num=who_work_in_IT.shape[0]
print("TOtal:",total_num)

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT
TOtal: 3


In [11]:
sort_in_decending=df.sort_values('salary',ascending=False)
print(sort_in_decending)
sort_in_decending.head(3)

   id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR
1   2   46   74131       IT
3   4   25   71090       IT
2   3   32   46023  Finance
9  10   28   35311       HR
8   9   28   32433    Sales
4   5   38   31685       HR
5   6   56   30769    Sales


id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR

In [12]:
print(salaries_arr)

df.loc[df['salary']>80000,'salary']=80000
print(df['salary'])

new_avg_salary=df['salary'].mean()
print(new_avg_salary)


[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
0    77191
1    74131
2    46023
3    71090
4    31685
5    30769
6    80000
7    80000
8    32433
9    35311
Name: salary, dtype: int64
55863.3
