In [ ]:
# Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.
import numpy as np
arr1=np.array([10,20,30])
arr2=np.array([[10,20,30],
               [40,50,60]
              ])
arr3=np.array([[[10,20,30],
               [40,50,60]],

               [[10,20,30],
               [40,50,60]],

               [[10,20,30],
               [40,50,60]]])
print(arr1)
print(arr2)
print(arr3)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


[10 20 30]
[[10 20 30]
 [40 50 60]]
[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
1
2
3
(3,)
(2, 3)
(3, 2, 3)


In [ ]:
""" Create:
an array of zeros of shape (3,3)
an array of ones of shape (2,5)
an array filled with 7"""

arr=np.zeros((3,3))
print(arr)

arr_1=np.ones((2,5))
print(arr_1)

arr_2=np.full_like((arr1),7)
print(arr_2)
arr_2=np.full_like((arr2),7)
print(arr_2)
arr_2=np.full_like((arr3),7)
print(arr_2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[7 7 7]
[[7 7 7]
 [7 7 7]]
[[[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]]]


In [ ]:
# Create an array of even numbers between 10 and 50 using arange.
arr=np.arange(2,51,2).reshape(5,5)
print(len(arr))
print(arr)

5
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]


In [ ]:
"""Create a 4×4 matrix from 0–15. Then , extract:
the first row
the last column
a 2×2 subarray from the center"""

arr=np.arange(0,16,1).reshape(4,4)
print(arr)

row_0=arr[0:1,]
print(row_0)

col_last=arr[::,3:]
print(col_last)

portion=arr[1:3,1:3]
print(portion)
print(portion.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 5  6]
 [ 9 10]]
(2, 2)


In [ ]:
# Add a 1D array [1,2,3] to each row of a 3×3 matrix.

arr=np.zeros((3,3))
arr_1=np.array([2,4,3])
result=arr+arr_1
print(result)

[[2. 4. 3.]
 [2. 4. 3.]
 [2. 4. 3.]]


In [ ]:
 """Given two arrays A and B, compute:
(A + B) / 2
A**2 + B**2"""
A=np.random.randint(1,15,size=(1,3))
B=np.random.randint(1,15,size=(1,3))
print(A)
print(B)
add=(A+B)/2
# print(add)
sqrt_a=A**2
print(sqrt_a)
sqrt_b=B**2
print(sqrt_b)
add1=sqrt_a+sqrt_b
print(add1)

[[12 11  3]]
[[ 4  7 14]]
[[144 121   9]]
[[ 16  49 196]]
[[160 170 205]]


In [ ]:
a=7**2
print(a)

49


In [ ]:
import numpy as np
np.random.seed(42)
print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]
