In [2]:
import numpy as np
arr= np.random.randint(1, 100,size=(10,5)) #sample=10 ,feature=5
arr.shape

(10, 5)

In [7]:
b=arr.reshape(5,10)
print(b)
b.shape
b.ndim


[[47  8  6 66 18 66 88 24  3 12]
 [88 28  5 49 65 76 80 69 16 91]
 [24  6 24 10 44 67 78 55  8  4]
 [92 31 88 34 94 18 55 23 55 51]
 [18 61 28  9 72 80 67 71 27  5]]


2

In [6]:
# shape change 2dm to 1dm (rowwise)
flatten=b.flatten()
print(flatten)
flatten.ndim
# column wise by ravel
column_wise_flattening=np.ravel(b,order='F')
print(column_wise_flattening)

[47  8  6 66 18 66 88 24  3 12 88 28  5 49 65 76 80 69 16 91 24  6 24 10
 44 67 78 55  8  4 92 31 88 34 94 18 55 23 55 51 18 61 28  9 72 80 67 71
 27  5]
[47 88 24 92 18  8 28  6 31 61  6  5 24 88 28 66 49 10 34  9 18 65 44 94
 72 66 76 67 18 80 88 80 78 55 67 24 69 55 23 71  3 16  8 55 27 12 91  4
 51  5]


In [8]:
a=np.random.randint(1, 10,size=(2,3))
b=np.random.randint(20, 30,size=(2,3))
print(a)
print(b)

[[7 4 9]
 [9 8 2]]
[[21 22 23]
 [22 23 26]]


In [13]:
# Concatenate  col wise same thakte hobe korar jonno
con_row=np.concatenate((a,b),axis=0)
print(con_row)
# row wise same thakte hobe concatenate korar jonno
con_col=np.concatenate((a,b),axis=1)
print(con_col)

[[ 7  4  9]
 [ 9  8  2]
 [21 22 23]
 [22 23 26]]
[[ 7  4  9 21 22 23]
 [ 9  8  2 22 23 26]]


In [16]:
# error

x=np.random.randint(1, 10,size=(2,3))
y=np.random.randint(1, 10,size=(1,3))
# row wise concat kora jabe bcz column same ache, but column wise kora jabe nh row same nai
con_cl=np.concatenate((x,y),axis=1)
print(con_cl)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [17]:
# Transpose

mat=np.array([[10,20,30],
              [40,50,60]])
transpose=mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


In [21]:
# array split 
a=np.random.randint(1, 10,size=(10,))
print(a)
splitted_array=np.array_split(a,3)
print(splitted_array)

# split use for equal division
splitted_array=np.split(a,3)

[1 1 3 2 1 7 7 7 6 4]
[array([1, 1, 3, 2], dtype=int32), array([1, 7, 7], dtype=int32), array([7, 6, 4], dtype=int32)]


In [25]:
# Arithmetic operator and mathematical function
# faster for vectorization
x=np.array([10,20,30])
y=np.array([2,3,4])

# add=np.add(x,y)
add=x+y
print(add)

sub=x-y
print(sub)

mul=x*y
print(mul)

div=x/y
print(div)

remainder=x%y
print(remainder)

[12 23 34]
[ 8 17 26]
[ 20  60 120]
[5.         6.66666667 7.5       ]
[0 2 2]


In [27]:
# Mathmatical function
# sin, cos, tan takes values in radian
sin_val= np.sin(x)
print(sin_val)

cos_val=np.cos(x)
# deg to radian theta*(pi/180)=radian
# radian to deg radian*(180/pi)=deg
deg_con=np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162]
[ 572.95779513 1145.91559026 1718.87338539]


In [30]:
# log log10 diya kotobar vag kora jay
base_10_log_val= np.log10(x)
print(base_10_log_val)

sqrt=np.sqrt(x)
print(sqrt)

[1.         1.30103    1.47712125]
[3.16227766 4.47213595 5.47722558]


In [35]:
x=np.array([10,20,30])
s=np.sum(x)
print(s)
# prefix sum
cumulativee=np.cumulative_sum(x)
print(cumulativee)

60
[10 30 60]


In [39]:
# Broadcasting kore sob element er sathe work kore
x=np.array([10,8,16,100])
result=x**2
# print(result)
# columns er size and vector er size same hote hobe
matrix=np.array([[10,20,30],
              [40,50,60]])
result=matrix+2
vector=np.array([1,2,3])
result=matrix+vector
print(result)

[[11 22 33]
 [41 52 63]]


In [44]:
# Logical function
x=np.array([10,20,30])
y=np.array([2,3,4])
greater_than=x>y
print(greater_than)

equal=x==y
print(equal)

# all shob true kina
# any jekono ekta true kina

print(np.all(greater_than))
print(np.any(equal))

[ True  True  True]
[False False False]
True
False


In [45]:
# Sorting 1d
# inplace sorting
x=np.array([10,8,16,100])
z=x.copy()
print(z)
z.sort()
print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [47]:
# copy sorting
print(x)
sort_arr=np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [49]:
# 2d array sorting
mat=np.array([[10,3,5],
              [8,4,9]])
# horizon axis=1
hor_sort=np.sort(mat,axis=1)
print(hor_sort)

# vertical axis=0
vert_sort=np.sort(mat,axis=0)
print(vert_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


In [51]:
print(x)

[ 10   8  16 100]


In [54]:
# Searching
# np.where (condition , x,y )if true x, otherwise replace with y
index=np.where(x==8)  #return index
print(index)
arr=np.where(x>8,x,0)   #return array
print(arr)

(array([1]),)
[ 10   0  16 100]


In [56]:
index=np.where(mat>8)  #return index
print(index)
arr=np.where(mat>8,mat,0)   #return array
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [59]:
# show result in index wise
x=np.array([10,8,16,100])
maximum_val=np.argmax(x)
print(maximum_val)
minimum_valueIndex=np.argmin(x)
print(minimum_valueIndex)

3
1


In [65]:
# Counting in ndarray
a=np.random.randint(1, 100,size=(100,))
print(a)

[50 45 73 11 74 16 60 35 22 39 81 60 69 80 89 17 44 97 77 75 65 60 77 86
 52 40 24 59 62 64 84 41 39 90 29 90 62 75  7 59 93 26 90 85  4 94 33 94
 21  7 96 19  5 45 47 30 67 74 29 54  1 20 74 19 96 35 70 20 22 54 10 23
  7 10 97 77 15 47 30 80 16  1 66 25 99 43 14 62 78 45 27 39 31  5 58 99
 76 32 25 16]


In [66]:
value_greater_than_60=np.count_nonzero(a>40)
print(value_greater_than_60)

57


In [71]:
unique_val,count=np.unique(a,return_counts=True)
print(unique_val)
print(count)

[ 1  4  5  7 10 11 14 15 16 17 19 20 21 22 23 24 25 26 27 29 30 31 32 33
 35 39 40 41 43 44 45 47 50 52 54 58 59 60 62 64 65 66 67 69 70 73 74 75
 76 77 78 80 81 84 85 86 89 90 93 94 96 97 99]
[2 1 2 3 2 1 1 1 3 1 2 2 1 2 1 1 2 1 1 2 2 1 1 1 2 3 1 1 1 1 3 2 1 1 2 1 2
 3 3 1 1 1 1 1 1 1 3 2 1 3 1 2 1 1 1 1 1 3 1 2 2 2 2]


In [6]:
# data load

data=np.genfromtxt('Book1.csv',delimiter=',',skip_header=1)
print(data)

[[  1.   85.   78.   90.    3.5   4. ]
 [  2.   90.   77.  100.    4.    3. ]
 [  3.   65.    nan  80.    2.    6. ]
 [  4.   70.   45.   86.    2.5   6. ]
 [  5.   85.   70.   70.    nan   4. ]
 [  6.   99.   65.   66.    4.    nan]
 [  7.   80.   99.    nan   3.    3.5]
 [  8.   55.   55.   45.    3.5   4. ]
 [  9.   90.   77.   80.    3.    2. ]
 [ 10.   60.   90.   50.    4.    8. ]
 [ 11.   85.   78.   90.    3.5   4. ]
 [ 12.   90.   77.  100.    4.    3. ]
 [ 13.   65.    nan  80.    2.    6. ]
 [ 14.   70.   45.   86.    2.5   6. ]
 [ 15.   85.   70.   70.    nan   4. ]
 [ 16.   99.   65.    nan   4.    nan]
 [ 17.    nan  99.   80.    5.    3.5]
 [ 18.   55.   55.   45.    3.5   4. ]
 [ 19.   90.   77.   80.    5.    2. ]
 [ 20.   60.   90.   50.    4.    8. ]]


In [13]:
# Statistics

math_marks=data[::,:1]
print(math_marks.T)

max_math_marks=np.max(math_marks)
print(max_math_marks)

min_math_marks=np.min(math_marks)
print(min_math_marks)

avg_math_marks=np.mean(math_marks)
print(avg_math_marks)

median_math_marks=np.median(math_marks)
print(median_math_marks)

# Standard deviation
std_of_marks=np.std(math_marks)
print(std_of_marks)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
  19. 20.]]
20.0
1.0
10.5
10.5
5.766281297335398


In [15]:
# correlation coefition
study_hour=np.array([2,4,5,7,8])
exam_score=np.array([65,75,78,88,92])
data=np.array([study_hour,exam_score])
correlation=np.corrcoef(data)
print(correlation)

[[1.         0.99859154]
 [0.99859154 1.        ]]


In [16]:
# Linear algebra 
# dot matrix er jonno a er column and b er row length same hote hobe
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])
dot_product=np.dot(A,B)
print(dot_product)
# trace
print(np.trace(B))

[[ 58  64]
 [139 154]]


In [22]:
# determinant
sq_mat=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
det_of_sq=np.linalg.det(sq_mat)
print(det_of_sq)

# matrix ranks
rank_sq=np.linalg.matrix_rank(sq_mat)
print(rank_sq)

0.0
2


In [1]:
#problem 1(Deep ML) Matrix-Vector Dot Product
import numpy as np
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	a=np.array(a)
	b=np.array(b)
	if a.shape[1]!=len(b):
		return -1
	return np.dot(a,b)

In [2]:
#problem 2 Transpose of a Matrix
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	a=np.array(a)
	b=a.T
	return b

In [ ]:
# Calculate Mean by Row or Column
import numpy as np
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	matrix=np.array(matrix)
	if mode=='row':
		means=np.mean(matrix,axis=1)
	else:
		means=np.mean(matrix,axis=0)
	return means